feat-18: redis-ai 추가
guri-tech/ML-Backend-Server pull request #27
Opened 2022-09-03 12:56 UTC by AstroNaut000

redis-ai로 model을 메모리에 적재하여
메모리에서 model을 불러와 빠르게 모델
호출 및 예측

Issues: #18

2022-09-03 14:13 UTC, lazychoi approved these changes
LGTM

2022-09-03 14:13 UTC, lazychoi commented on .gitignore
> +/home/jb/ML-Backend-Server/hotelAPI/.env
.env 파일은 올리면 안될 것 같아요.
ttest.ipynb, nohop.out, mlruns/ 도 안 올리는 게 좋을 것 같아요

2022-09-03 14:13 UTC, lazychoi commented on hotelAPI/utils/hotel_utils.py
>      mlflow.set_tracking_uri("http://127.0.0.1:5000")
환경변수를 이용하면 좋을 것 같아요

2022-09-03 14:13 UTC, lazychoi commented on train_prefect/tasks.py
> +
같은 코드가 중복되니 나중에 함수로 빼면 좋을 것 같아요

2022-09-04 01:32 UTC, Ilevk requested changes
수정해주세요

2022-09-04 01:32 UTC, Ilevk commented on train_prefect/train_flow.py
> +    x_data, y_data = preprocessing(df)
1. 여기에서 전처리기 (ct) 반환받고

2022-09-04 01:32 UTC, Ilevk commented on train_prefect/train_flow.py
> +    trained_model, metrics = train_model(model, x_data, y_data)
2. 여기에서 반환받은 모델(clf)랑 같이

2022-09-04 01:32 UTC, Ilevk commented on train_prefect/train_flow.py
>      current_version = log_model(trained_model, model_name, params, metrics, eval_metric)
3. 여기에 전달해서 sklearn pipeline으로 만들고 logging

2022-09-04 01:32 UTC, Ilevk commented on train_prefect/train_flow.py
> +    change_production_model(trained_model,model_name, current_version, eval_metric,x_data)
4. 여기에서 로깅한 pipeline 서빙
- x_data를 전달하기 보다는 차라리 차원(data_shape)을 전달 왜냐하면 객체 전달할 때 실제로 피클링(cloud pickle) 돼서 전달된다

2022-09-04 01:40 UTC, Ilevk commented on hotelAPI/routers/hotel_router.py
> +    redisai_client.tensorset('hotel_input',preprocessor.transform(df).astype(np.float32))
input tensor key를 고민해보기, ex) uuid, hash

2022-09-04 02:00 UTC, Ilevk commented on hotelAPI/routers/hotel_router.py
> +    redisai_client = rai.Client(host = 'localhost', port = 6379)
서버가 시작될 때 한번만 생성하도록

https://fastapi.tiangolo.com/advanced/events/

2022-09-04 12:36 UTC, pastnfast commented on train_prefect/tasks.py
> +    redisai_client = rai.Client(host = 'localhost',port = 6379)
나중에 이 부분도 환경변수로 숨겨주세요.

2022-09-15 02:26 UTC, pastnfast approved these changes
LGTM

2022-09-15 02:27 UTC, merged